sudo: true
language: node_js
node_js:
  - "stable"
git:
  quiet: true
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
after_script:
  - cd build
  - find . -type f -exec curl --user "$FTP_USER:$FTP_PASS" --ftp-create-dirs -T {} ftp://$FTP_ADDRESS/{} \;
before_deploy: cp .cpanel.yml ./build/.cpanel.yml
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
#before_install:
#- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
#  -in travis_rsa.enc -out travis_rsa -d
#- chmod +600 travis_rsa
#- mv travis_rsa ~/.ssh/id_rsa
#- cat server.pub >> $HOME/.ssh/known_hosts
